# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'rag_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rag_service.proto\x12\x0cLLMWorkerAPI\"B\n\x11NewMessageRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\x03\x12\x14\n\x0cuser_message\x18\x02 \x01(\t\"\x1a\n\nTokenChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1f\n\nCompletion\x12\x11\n\tfull_text\x18\x01 \x01(\t\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xbc\x01\n\x17NewMessageChunkResponse\x12)\n\x05token\x18\x01 \x01(\x0b\x32\x18.LLMWorkerAPI.TokenChunkH\x00\x12.\n\ncompletion\x18\x02 \x01(\x0b\x32\x18.LLMWorkerAPI.CompletionH\x00\x12$\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x13.LLMWorkerAPI.ErrorH\x00\x12\x17\n\x0f\x63onversation_id\x18\x04 \x01(\x03\x42\x07\n\x05\x65vent2k\n\x0eMessageService\x12Y\n\rGenerateReply\x12\x1f.LLMWorkerAPI.NewMessageRequest\x1a%.LLMWorkerAPI.NewMessageChunkResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEWMESSAGEREQUEST']._serialized_start=35
  _globals['_NEWMESSAGEREQUEST']._serialized_end=101
  _globals['_TOKENCHUNK']._serialized_start=103
  _globals['_TOKENCHUNK']._serialized_end=129
  _globals['_COMPLETION']._serialized_start=131
  _globals['_COMPLETION']._serialized_end=162
  _globals['_ERROR']._serialized_start=164
  _globals['_ERROR']._serialized_end=188
  _globals['_NEWMESSAGECHUNKRESPONSE']._serialized_start=191
  _globals['_NEWMESSAGECHUNKRESPONSE']._serialized_end=379
  _globals['_MESSAGESERVICE']._serialized_start=381
  _globals['_MESSAGESERVICE']._serialized_end=488
# @@protoc_insertion_point(module_scope)
